name: Build and release
on: push
jobs:
  build-project:
    name: Installing my packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build static website
        run: npm run build
      - name: Upload static website
        uses: actions/upload-artifact@v2
        with:
          name: static-site
          path: out/